# Generated by Django 5.0 on 2023-12-15 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airlines", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="airplane",
            old_name="passenger_count",
            new_name="passenger_assumptions",
        ),
    ]
